var LatLon = require('geodesy/latlon-spherical.js');
var png = require('./png');
var graphics = require('./graphics');
// Generated by the wscript from config.html; served to the webview as a data URI.
var configPageHtml = require('./config_page');
var MAP_WIDTH = 200;
var MAP_HEIGHT = 150;

// State Variables
// Sized so one chunk (plus dictionary overhead) fits the watch inbox, which
// the C side opens at CHUNK_SIZE + overhead. Fewer, larger messages mean
// fewer radio wakeups per frame. Aplite gets a smaller inbox to fit its RAM;
// adjusted after platform detection in the ready handler.
var CHUNK_SIZE = 7100;
var gpsInterval = 5;
var gpxTrack = [];
var currentLocation = null;
var currentLL = null;
var currentZoom = 17;
var isSendingMap = false;
// The watch reports whether its map pixels can currently be seen (dashboard,
// menus and the big-nav popup hide them). While hidden, rendering and
// streaming frames would burn radio time for pixels nobody sees.
var mapVisibleOnWatch = true;

// Last map image successfully transmitted to the watch, so that an unchanged
// viewport does not get re-rendered and re-sent on every GPS fix. Holds the
// centre in world pixels plus a signature of everything else the render
// depends on; null means "no valid image on the watch, always redraw".
var lastRender = null;
var pendingRender = null;
// Hash of the last frame the watch fully received; frames hashing the same
// are pixel-identical and skipped. null means "watch content unknown".
var lastDeliveredFrameHash = null;
// A fix that moves the centre by less than this many pixels produces a
// visually identical image, so it is not worth a 30 KB transfer. At zoom 17
// one pixel is roughly a metre, which is well inside GPS jitter.
var RENDER_PIXEL_THRESHOLD = 2;
var gpsWatchId = null;
var gpsPollTimer = null;
var gpsErrorActive = false; // suppresses repeat GPS-error messages
// Idle cadence for one-shot fixes. Duty-cycling only beats a continuous
// watch when the receiver gets to sleep for a long stretch between fixes.
var IDLE_GPS_POLL_MS = 30000;
var platform = "basalt";

function updateMapDimensions() {
  var isFullscreen = localStorage.getItem('fullscreen') === 'true';
  if (platform === "emery") {
    MAP_WIDTH = 200;
    MAP_HEIGHT = isFullscreen ? 228 : 150;
  } else if (platform === "chalk") {
    MAP_WIDTH = 180;
    MAP_HEIGHT = isFullscreen ? 180 : 114;
  } else { // basalt, aplite
    MAP_WIDTH = 144;
    MAP_HEIGHT = isFullscreen ? 168 : 112;
  }
  graphics.setDimensions(MAP_WIDTH, MAP_HEIGHT);
  console.log("Updated map dimensions to: " + MAP_WIDTH + "x" + MAP_HEIGHT + " (Fullscreen: " + isFullscreen + ")");
}

// Navigation & Recording State
var isNavigating = false;
var recordedTrack = [];
// Persistence of the recorded track is split into a base array plus a small
// tail: appends re-serialize only the tail, and the whole track is rewritten
// just once per TAIL_LIMIT points, so the per-point write cost stays bounded
// as the trip grows.
var RECORDED_TAIL_LIMIT = 40; // one full rewrite per ~400m walked
var recordedTrackTailCount = 0;
var currentSpeed = 0;
var currentHeading = -1;

// Haptic feedback states
var lastVibratedTurnIdx = -1;
var hasVibratedOffRoute = false;

// Average speed & walked route state
var totalMovingDistance = 0;
var totalMovingTimeSec = 0;
var lastPositionTime = null;
var lastPositionCoords = null;
var closestTrackPointIdx = -1;

// Base64 helpers. PebbleKit JS runs in a sandbox inside the phone's Pebble app
// that exposes only a restricted subset of HTML5 APIs (XMLHttpRequest,
// localStorage, geolocation, timers, logging) -- btoa/atob are not included,
// and support differs between the iOS and Android apps. Encode/decode by hand.
var B64_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
var B64_LOOKUP = (function() {
  var lookup = {};
  for (var i = 0; i < B64_CHARS.length; i++) {
    lookup[B64_CHARS.charAt(i)] = i;
  }
  return lookup;
})();

// Utility: Convert ArrayBuffer to Base64 string
function arrayBufferToBase64(buffer) {
  var bytes = new Uint8Array(buffer);
  var len = bytes.length;
  var parts = [];
  var chunk = '';
  var i;

  for (i = 0; i + 2 < len; i += 3) {
    var triplet = (bytes[i] << 16) | (bytes[i + 1] << 8) | bytes[i + 2];
    chunk +=
      B64_CHARS.charAt((triplet >> 18) & 63) +
      B64_CHARS.charAt((triplet >> 12) & 63) +
      B64_CHARS.charAt((triplet >> 6) & 63) +
      B64_CHARS.charAt(triplet & 63);
    // Flush periodically to bound peak string size on a ~30KB tile.
    if (chunk.length >= 8192) {
      parts.push(chunk);
      chunk = '';
    }
  }

  // Tail: 1 or 2 leftover bytes get padded with '='
  var remaining = len - i;
  if (remaining === 1) {
    chunk +=
      B64_CHARS.charAt((bytes[i] >> 2) & 63) +
      B64_CHARS.charAt((bytes[i] << 4) & 63) +
      '==';
  } else if (remaining === 2) {
    chunk +=
      B64_CHARS.charAt((bytes[i] >> 2) & 63) +
      B64_CHARS.charAt(((bytes[i] << 4) | (bytes[i + 1] >> 4)) & 63) +
      B64_CHARS.charAt((bytes[i + 1] << 2) & 63) +
      '=';
  }
  parts.push(chunk);

  return parts.join('');
}

// Utility: Convert Base64 string to Uint8Array
function base64ToUint8Array(base64) {
  // Tolerate padding and stray whitespace/newlines
  var clean = base64.replace(/[\s=]/g, '');
  var len = clean.length;
  var outLen = Math.floor((len * 3) / 4);
  var bytes = new Uint8Array(outLen);
  var acc = 0;
  var accBits = 0;
  var outIdx = 0;

  for (var i = 0; i < len; i++) {
    var value = B64_LOOKUP[clean.charAt(i)];
    if (value === undefined) {
      throw new Error('Invalid base64 character at index ' + i);
    }
    acc = (acc << 6) | value;
    accBits += 6;
    if (accBits >= 8) {
      accBits -= 8;
      bytes[outIdx++] = (acc >> accBits) & 0xff;
    }
  }

  return outIdx === outLen ? bytes : bytes.subarray(0, outIdx);
}

// Status values as last acknowledged by the watch. Status payloads are
// diffed against this so unchanged keys (language, settings, unchanged nav
// text) are not retransmitted every fix -- each avoided key also avoids the
// redraw/persist work its arrival triggers on the watch.
var lastSentStatus = {};

function resetStatusCache() {
  lastSentStatus = {};
}

// Sends only the keys whose values differ from what the watch already has.
// VIBRATE_ALERT is an event, not state, and always passes through. Keys are
// recorded only after the watch ACKs, so a failed send retries them later.
function sendStatusMessage(payload, onSuccess, onFailure) {
  var delta = {};
  var changedKeys = [];
  for (var key in payload) {
    if (!payload.hasOwnProperty(key)) continue;
    if (key === 'VIBRATE_ALERT' || payload[key] !== lastSentStatus[key]) {
      delta[key] = payload[key];
      changedKeys.push(key);
    }
  }

  if (changedKeys.length === 0) {
    if (onSuccess) onSuccess();
    return;
  }

  // sendAppMessage throws synchronously on unserializable values (e.g. an
  // int32-overflowing number); uncaught, that kills the GPS callback chain.
  try {
    Pebble.sendAppMessage(delta, function() {
      for (var i = 0; i < changedKeys.length; i++) {
        if (changedKeys[i] !== 'VIBRATE_ALERT') {
          lastSentStatus[changedKeys[i]] = delta[changedKeys[i]];
        }
      }
      if (onSuccess) onSuccess();
    }, function(e) {
      if (onFailure) onFailure(e);
    });
  } catch (err) {
    console.log('sendStatusMessage failed: ' + err);
    if (onFailure) onFailure(err);
  }
}

// Haversine formula to compute distance in meters
function haversineDistance(lat1, lon1, lat2, lon2) {
  var R = 6371000; // Radius of the Earth in meters
  var dLat = ((lat2 - lat1) * Math.PI) / 180;
  var dLon = ((lon2 - lon1) * Math.PI) / 180;
  var a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

// Calculate bearing between two points (0 to 360)
function getBearing(lat1, lon1, lat2, lon2) {
  var dLon = ((lon2 - lon1) * Math.PI) / 180;
  var lat1Rad = (lat1 * Math.PI) / 180;
  var lat2Rad = (lat2 * Math.PI) / 180;
  var y = Math.sin(dLon) * Math.cos(lat2Rad);
  var x =
    Math.cos(lat1Rad) * Math.sin(lat2Rad) -
    Math.sin(lat1Rad) * Math.cos(lat2Rad) * Math.cos(dLon);
  var brng = (Math.atan2(y, x) * 180) / Math.PI;
  return (brng + 360) % 360;
}

// Per-track precomputation. All whole-track quantities (cumulative distance,
// elevation gain/loss, segment bearings, LatLon objects for the geodesy
// library) are functions of the route alone and are built once per track
// change, not per GPS fix.
var trackIndex = null;

function buildTrackIndex(points) {
  if (!points || points.length === 0) {
    trackIndex = null;
    return;
  }
  var n = points.length;
  var ll = new Array(n);
  var cumDist = new Array(n); // meters from start to point i
  var cumGain = new Array(n); // climb accumulated up to point i
  var cumLoss = new Array(n);
  var bearings = new Array(n); // bearing of segment i -> i+1

  ll[0] = new LatLon(points[0].lat, points[0].lon);
  cumDist[0] = 0;
  cumGain[0] = 0;
  cumLoss[0] = 0;

  for (var i = 1; i < n; i++) {
    ll[i] = new LatLon(points[i].lat, points[i].lon);
    cumDist[i] = cumDist[i - 1] +
      haversineDistance(points[i - 1].lat, points[i - 1].lon, points[i].lat, points[i].lon);
    var gain = 0;
    var loss = 0;
    if (points[i - 1].ele !== undefined && points[i].ele !== undefined) {
      var d = points[i].ele - points[i - 1].ele;
      if (d > 0) gain = d;
      else loss = -d;
    }
    cumGain[i] = cumGain[i - 1] + gain;
    cumLoss[i] = cumLoss[i - 1] + loss;
  }

  for (var j = 0; j < n - 1; j++) {
    bearings[j] = getBearing(points[j].lat, points[j].lon, points[j + 1].lat, points[j + 1].lon);
  }
  bearings[n - 1] = n > 1 ? bearings[n - 2] : 0;

  trackIndex = { ll: ll, cumDist: cumDist, cumGain: cumGain, cumLoss: cumLoss, bearings: bearings };
}

// Closest point/section on the track within point indices [startIdx, endIdx].
function findClosestOnTrack(startIdx, endIdx) {
  var ll = trackIndex.ll;
  var p1 = ll[startIdx];
  var minDist = currentLL.distanceTo(p1);
  var closestIdx = startIdx;

  for (var k = startIdx + 1; k <= endIdx; k++) {
    var p2 = ll[k];

    // Are we close to a point?
    var distanceToPoint = currentLL.distanceTo(p2);
    if (distanceToPoint < minDist) {
      minDist = distanceToPoint;
      closestIdx = k;
    }

    // Are we close to a line / section?
    var distanceToLine = Math.abs(currentLL.crossTrackDistanceTo(p1, p2));
    if (distanceToLine < minDist) {
      var along = currentLL.alongTrackDistanceTo(p1, p2);
      var sectionLength = p1.distanceTo(p2);
      if (along > 0 && along < sectionLength) {
        minDist = distanceToLine;
        closestIdx = k - 1;
      }
    }
    p1 = p2;
  }
  return { minDist: minDist, closestIdx: closestIdx };
}

// Get tile URL based on chosen map source
function getTileUrl(z, x, y) {
  var mapSource = localStorage.getItem('mapSource') || 'opentopomap';
  var subdomains, sub;

  // Custom tile server: URL template with {z}/{x}/{y} placeholders,
  // e.g. http://localhost:8747/{z}/{x}/{y}.png
  if (mapSource === 'custom') {
    var template = localStorage.getItem('customTileUrl');
    if (template) {
      return template.replace('{z}', z).replace('{x}', x).replace('{y}', y);
    }
    mapSource = 'opentopomap';
  }

  // 'hikebikemap' kept as a legacy alias: the old tiles.wmflabs.org server was
  // decommissioned by Wikimedia, so previously-saved settings now resolve to CyclOSM.
  if (mapSource === 'cyclosm' || mapSource === 'hikebikemap') {
    subdomains = ['a', 'b', 'c'];
    sub = subdomains[Math.floor(Math.random() * 3)];
    return 'https://' + sub + '.tile-cyclosm.openstreetmap.fr/cyclosm/' + z + '/' + x + '/' + y + '.png';
  } else if (mapSource === 'mtbmap') {
    return 'https://tile.mtbmap.cz/mtbmap_tiles/' + z + '/' + x + '/' + y + '.png';
  } else if (mapSource === 'osm') {
    subdomains = ['a', 'b', 'c'];
    sub = subdomains[Math.floor(Math.random() * 3)];
    return 'https://' + sub + '.tile.openstreetmap.org/' + z + '/' + x + '/' + y + '.png';
  } else { // opentopomap
    subdomains = ['a', 'b', 'c'];
    sub = subdomains[Math.floor(Math.random() * 3)];
    return 'https://' + sub + '.tile.opentopomap.org/' + z + '/' + x + '/' + y + '.png';
  }
}

// Initialize the Pebble application
Pebble.addEventListener('ready', function() {
  if (typeof Pebble !== 'undefined' && Pebble.getActiveWatchInfo) {
    try {
      var info = Pebble.getActiveWatchInfo();
      platform = info.platform || "basalt";
    } catch(e) {
      console.log("Error getting watch info: " + e);
    }
  }
  graphics.initMapDimensions(platform);
  if (platform === "aplite") {
    CHUNK_SIZE = 3000; // matches the smaller inbox the C side opens on aplite
  }

  // Load settings from LocalStorage
  var storedInterval = localStorage.getItem('gpsInterval');
  if (storedInterval) gpsInterval = parseInt(storedInterval);
  
  // Update map dimensions based on loaded settings
  updateMapDimensions();
  if (storedInterval) gpsInterval = parseInt(storedInterval);

  loadTileIndex();
  console.log('Tile cache: ' + tileCacheDebugString());
  
  var storedTrack = localStorage.getItem('gpxTrack');
  if (storedTrack) {
    try {
      gpxTrack = JSON.parse(storedTrack);
      console.log('Loaded GPX track from storage: ' + gpxTrack.length + ' points.');
    } catch (e) {
      gpxTrack = [];
    }
  }

  // Load walked stats from LocalStorage to allow seamless resumption
  var storedMovingDist = localStorage.getItem('totalMovingDistance');
  if (storedMovingDist) totalMovingDistance = parseFloat(storedMovingDist);
  
  var storedMovingTime = localStorage.getItem('totalMovingTimeSec');
  if (storedMovingTime) totalMovingTimeSec = parseFloat(storedMovingTime);
  
  var storedClosestIdx = localStorage.getItem('closestTrackPointIdx');
  if (storedClosestIdx) closestTrackPointIdx = parseInt(storedClosestIdx);

  isNavigating = localStorage.getItem('isNavigating') === 'true';
  var storedRecordedTrack = localStorage.getItem('recordedTrack');
  if (storedRecordedTrack) {
    try {
      recordedTrack = JSON.parse(storedRecordedTrack);
    } catch (e) {
      recordedTrack = [];
    }
  }
  try {
    var storedTail = JSON.parse(localStorage.getItem('recordedTrackTail') || '[]');
    recordedTrack = recordedTrack.concat(storedTail);
    recordedTrackTailCount = storedTail.length;
  } catch (e) {
    recordedTrackTailCount = 0;
  }
  if (recordedTrack.length > 0) {
    console.log('Loaded recorded track: ' + recordedTrack.length + ' points.');
  }

  // Load active route points if set
  var activeRouteIdStr = localStorage.getItem('activeRouteId');
  if (activeRouteIdStr) {
    var activeId = parseInt(activeRouteIdStr, 10);
    var savedRoutes = [];
    try {
      savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
    } catch (e) {
      savedRoutes = [];
    }
    if (savedRoutes && Array.isArray(savedRoutes)) {
      var activeRoute = savedRoutes.filter(function(r) { return (r.id & 0xFFFFFFFF) === (activeId & 0xFFFFFFFF); })[0];
      if (activeRoute) {
        gpxTrack = activeRoute.points || [];
        console.log('Loaded active route: ' + activeRoute.name + ' (' + gpxTrack.length + ' points).');
      } else {
        gpxTrack = [];
      }
    } else {
      gpxTrack = [];
    }
  } else {
    // Legacy fallback
    var storedTrackFallback = localStorage.getItem('gpxTrack');
    if (storedTrackFallback) {
      try {
        gpxTrack = JSON.parse(storedTrackFallback);
        console.log('Loaded legacy GPX track: ' + gpxTrack.length + ' points.');
      } catch (e) {
        gpxTrack = [];
      }
    }
  }

  buildTrackIndex(gpxTrack);

  // Start GPS tracking
  restartGPSTracking();

  // Sync routes to watch on startup
  setTimeout(syncRoutesToWatch, 1000);
});

// Helper to open the configuration url with all required parameters
function openConfigPage() {
  var interval = localStorage.getItem('gpsInterval') || '5';
  var lang = localStorage.getItem('language') || 'en';
  var mapSource = localStorage.getItem('mapSource') || 'opentopomap';
  var fullscreen = localStorage.getItem('fullscreen') || 'false';
  var showBreadcrumbs = localStorage.getItem('showBreadcrumbs') !== 'false';
  var savedTrips = JSON.parse(localStorage.getItem('savedTrips') || '[]');
  
  // Keep only the latest 3 trips for the settings page to prevent URL overflow
  var recentTrips = savedTrips.slice(-3);
  
  var tripsMeta = recentTrips.map(function(t) {
    return {
      id: t.id,
      date: t.date,
      distance: t.distance,
      duration: t.duration,
      pointsCount: t.points ? t.points.length : 0,
      pointsStr: compressPointsCompact(t.points)
    };
  });

  // Serialize saved routes list metadata
  var savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
  var routesMeta = savedRoutes.map(function(r) {
    var dist = 0;
    if (r.points) {
      for (var k = 0; k < r.points.length - 1; k++) {
        dist += haversineDistance(r.points[k].lat, r.points[k].lon, r.points[k+1].lat, r.points[k+1].lon);
      }
    }
    return {
      id: r.id,
      name: r.name,
      distance: dist,
      pointsCount: r.points ? r.points.length : 0
    };
  });
  
  // The page reads these through getQueryParam(), so every value is a string.
  var params = {
    interval: interval,
    lang: lang,
    map: mapSource,
    custom_tile_url: localStorage.getItem('customTileUrl') || '',
    fullscreen: fullscreen,
    show_breadcrumbs: showBreadcrumbs ? 'true' : 'false',
    nav_view_mode: localStorage.getItem('navViewMode') || '0',
    dashboard_fields: localStorage.getItem('dashboardFields') || '31',
    is_nav: isNavigating ? 'true' : 'false',
    routes: JSON.stringify(routesMeta),
    active_route_id: localStorage.getItem('activeRouteId') || '0',
    trips: JSON.stringify(tripsMeta)
  };

  // A function replacement keeps route names containing $& or $' literal.
  var injection = 'window.TOPONAV_PARAMS = ' + JSON.stringify(params) + ';';
  var html = configPageHtml.replace('/*$$PARAMS$$*/', function() { return injection; });
  var url = 'data:text/html;charset=utf-8,' + encodeURIComponent(html);

  console.log('Opening bundled config page. Data URI length: ' + url.length);
  Pebble.openURL(url);
}

// Sync routes list to watch
function syncRoutesToWatch() {
  var savedRoutes = [];
  try {
    savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
  } catch (e) {
    savedRoutes = [];
  }
  var activeRouteId = parseInt(localStorage.getItem('activeRouteId') || '0', 10);
  
  if (!savedRoutes || !Array.isArray(savedRoutes)) {
    savedRoutes = [];
  }
  
  console.log('Syncing ' + savedRoutes.length + ' routes to watch. Active ID: ' + activeRouteId);
  
  Pebble.sendAppMessage({
    ACTIVE_ROUTE_ID: activeRouteId
  }, function() {
    Pebble.sendAppMessage({
      ROUTE_COUNT: savedRoutes.length
    }, function() {
      var idx = 0;
      function sendNext() {
        if (idx >= savedRoutes.length || idx >= 15) {
          console.log('Route list fully synced to watch.');
          return;
        }
        var route = savedRoutes[idx];
        Pebble.sendAppMessage({
          ROUTE_INDEX: idx,
          ROUTE_ID: route.id,
          ROUTE_NAME: route.name.substring(0, 31)
        }, function() {
          idx++;
          setTimeout(sendNext, 100);
        }, function(err) {
          console.warn('Failed to sync route index ' + idx + ', retrying...');
          setTimeout(sendNext, 250);
        });
      }
      if (savedRoutes.length > 0) {
        sendNext();
      }
    });
  });
}

function activateSavedRoute(routeId) {
  var savedRoutes = [];
  try {
    savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
  } catch (e) {
    savedRoutes = [];
  }
  var foundRoute = null;
  if (savedRoutes && Array.isArray(savedRoutes)) {
    foundRoute = savedRoutes.filter(function(r) { return (r.id & 0xFFFFFFFF) === (routeId & 0xFFFFFFFF); })[0];
  }
  
  if (foundRoute) {
    if (isNavigating) {
      stopRecording(true);
    }

    localStorage.setItem('activeRouteId', routeId.toString());
    gpxTrack = foundRoute.points || [];
    buildTrackIndex(gpxTrack);
    localStorage.setItem('gpxTrack', JSON.stringify(gpxTrack));
    console.log('Activated route: ' + foundRoute.name);
    
    // Reset navigation stats for the new route
    totalMovingDistance = 0;
    totalMovingTimeSec = 0;
    localStorage.removeItem('totalMovingDistance');
    localStorage.removeItem('totalMovingTimeSec');
    closestTrackPointIdx = -1;
    localStorage.removeItem('closestTrackPointIdx');
    lastPositionTime = null;
    lastPositionCoords = null;
    lastVibratedTurnIdx = -1;
    hasVibratedOffRoute = false;
    
    if (gpxTrack.length > 0) {
      cacheTrackTiles(gpxTrack);
    }
    
    startRecording();
  } else if (routeId === 0) {
    localStorage.setItem('activeRouteId', '0');
    gpxTrack = [];
    buildTrackIndex(gpxTrack);
    localStorage.setItem('gpxTrack', JSON.stringify(gpxTrack));
    console.log('Deactivated current route.');
    
    // Reset navigation stats
    totalMovingDistance = 0;
    totalMovingTimeSec = 0;
    localStorage.removeItem('totalMovingDistance');
    localStorage.removeItem('totalMovingTimeSec');
    closestTrackPointIdx = -1;
    localStorage.removeItem('closestTrackPointIdx');
    lastPositionTime = null;
    lastPositionCoords = null;
    lastVibratedTurnIdx = -1;
    hasVibratedOffRoute = false;
    
    if (isNavigating) {
      stopRecording(true);
    }
  }
  
  syncRoutesToWatch();
  updateWatchNavigationAndMap();
}

function deleteSavedRoute(routeId) {
  var savedRoutes = [];
  try {
    savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
  } catch (e) {
    savedRoutes = [];
  }
  var updated = [];
  if (savedRoutes && Array.isArray(savedRoutes)) {
    updated = savedRoutes.filter(function(r) {
      return (r.id & 0xFFFFFFFF) !== (routeId & 0xFFFFFFFF);
    });
  }
  localStorage.setItem('savedRoutes', JSON.stringify(updated));
  console.log('Deleted route ID: ' + routeId);
  
  var activeId = parseInt(localStorage.getItem('activeRouteId') || '0', 10);
  if ((activeId & 0xFFFFFFFF) === (routeId & 0xFFFFFFFF)) {
    activateSavedRoute(0);
  } else {
    syncRoutesToWatch();
  }
}

// Coordinate delta compression for URL transmission
function compressTrack(points) {
  if (!points || points.length === 0) return '';
  var segments = [];
  var lastLat = 0;
  var lastLon = 0;
  var lastEle = 0;
  var lastTime = 0;
  
  for (var i = 0; i < points.length; i++) {
    var p = points[i];
    var latVal = Math.round(p.lat * 1000000);
    var lonVal = Math.round(p.lon * 1000000);
    var eleVal = Math.round(p.ele || 0);
    var timeVal = Math.round(p.time || 0);
    
    if (i === 0) {
      segments.push(latVal + ',' + lonVal + ',' + eleVal + ',' + timeVal);
    } else {
      var dLat = latVal - lastLat;
      var dLon = lonVal - lastLon;
      var dEle = eleVal - lastEle;
      var dTime = timeVal - lastTime;
      segments.push(dLat + ',' + dLon + ',' + dEle + ',' + dTime);
    }
    
    lastLat = latVal;
    lastLon = lonVal;
    lastEle = eleVal;
    lastTime = timeVal;
  }
  return segments.join('|');
}

function decimatePoints(points, maxPoints) {
  if (!points || points.length <= maxPoints) return points;
  var decimated = [];
  var step = Math.ceil((points.length - 1) / (maxPoints - 1));
  for (var i = 0; i < points.length - 1; i += step) {
    decimated.push(points[i]);
  }
  decimated.push(points[points.length - 1]);
  return decimated;
}

function compressPointsCompact(points) {
  if (!points || points.length === 0) return '';
  var maxPts = 50; // Decimate to max 50 points for settings view and download
  var pts = decimatePoints(points, maxPts);
  
  var segments = [];
  var lastLat = 0;
  var lastLon = 0;
  var lastEle = 0;
  var lastTime = 0;
  
  for (var i = 0; i < pts.length; i++) {
    var p = pts[i];
    var latVal = Math.round(p.lat * 100000);
    var lonVal = Math.round(p.lon * 100000);
    var eleVal = Math.round(p.ele || 0);
    var timeVal = Math.round((p.time || 0) / 1000); // Store time in seconds
    
    if (i === 0) {
      segments.push(latVal.toString(36) + ',' + lonVal.toString(36) + ',' + eleVal.toString(36) + ',' + timeVal.toString(36));
    } else {
      var dLat = latVal - lastLat;
      var dLon = lonVal - lastLon;
      var dEle = eleVal - lastEle;
      var dTime = timeVal - lastTime;
      segments.push(dLat.toString(36) + ',' + dLon.toString(36) + ',' + dEle.toString(36) + ',' + dTime.toString(36));
    }
    
    lastLat = latVal;
    lastLon = lonVal;
    lastEle = eleVal;
    lastTime = timeVal;
  }
  return segments.join('|');
}

function deleteSavedTrip(tripId) {
  var savedTrips = JSON.parse(localStorage.getItem('savedTrips') || '[]');
  var updated = savedTrips.filter(function(t) {
    return t.id !== tripId;
  });
  localStorage.setItem('savedTrips', JSON.stringify(updated));
}

function startRecording() {
  isNavigating = true;
  localStorage.setItem('isNavigating', 'true');

  recordedTrack = [];
  recordedTrackTailCount = 0;
  localStorage.setItem('recordedTrack', '[]');
  localStorage.setItem('recordedTrackTail', '[]');
  
  totalMovingDistance = 0;
  totalMovingTimeSec = 0;
  localStorage.setItem('totalMovingDistance', 0);
  localStorage.setItem('totalMovingTimeSec', 0);
  
  closestTrackPointIdx = -1;
  localStorage.setItem('closestTrackPointIdx', -1);
  lastPositionTime = null;
  lastPositionCoords = null;
  
  // Confirm start with short vibe
  sendStatusMessage({
    RECORDING_STATE: 1,
    VIBRATE_ALERT: 1
  });

  restartGPSTracking(); // switch from idle polling to continuous tracking
  updateWatchNavigationAndMap();
}

function stopRecording(save) {
  isNavigating = false;
  localStorage.setItem('isNavigating', 'false');
  
  if (save && recordedTrack.length > 0) {
    var savedTrips = JSON.parse(localStorage.getItem('savedTrips') || '[]');
    var newTrip = {
      id: Date.now(),
      date: new Date().toISOString(),
      distance: totalMovingDistance,
      duration: totalMovingTimeSec,
      points: recordedTrack
    };
    savedTrips.push(newTrip);
    localStorage.setItem('savedTrips', JSON.stringify(savedTrips));
    console.log('Saved new trip with ' + recordedTrack.length + ' points.');
  }
  
  recordedTrack = [];
  recordedTrackTailCount = 0;
  localStorage.setItem('recordedTrack', '[]');
  localStorage.setItem('recordedTrackTail', '[]');

  // Confirm stop with double vibe
  sendStatusMessage({
    RECORDING_STATE: 0,
    VIBRATE_ALERT: 2
  });

  restartGPSTracking(); // drop back from continuous tracking to idle polling
  updateWatchNavigationAndMap();
}

function toggleRecordingState() {
  if (isNavigating) {
    stopRecording(true);
  } else {
    startRecording();
  }
}

// Settings config page trigger
Pebble.addEventListener('showConfiguration', function() {
  openConfigPage();
});

// Settings config page closed
Pebble.addEventListener('webviewclosed', function(e) {
  if (e && e.response) {
    try {
      var responseStr = decodeURIComponent(e.response);
      console.log('WebView closed response: ' + responseStr);
      
      if (responseStr === 'toggle_nav') {
        toggleRecordingState();
        setTimeout(function() {
          openConfigPage();
        }, 350);
        return;
      }
      
      if (responseStr.indexOf('delete_') === 0 && responseStr.indexOf('delete_route_') === -1) {
        var deleteId = parseInt(responseStr.substring(7), 10);
        deleteSavedTrip(deleteId);
        setTimeout(function() {
          openConfigPage();
        }, 350);
        return;
      }
      

      
      if (responseStr.indexOf('delete_route_') === 0) {
        var delRouteId = parseInt(responseStr.substring(13), 10);
        deleteSavedRoute(delRouteId);
        setTimeout(function() {
          openConfigPage();
        }, 350);
        return;
      }
      
      if (responseStr.indexOf('activate_route_') === 0) {
        var actRouteId = parseInt(responseStr.substring(15), 10);
        activateSavedRoute(actRouteId);
        setTimeout(function() {
          openConfigPage();
        }, 350);
        return;
      }
      
      var settings = JSON.parse(responseStr);
      console.log('Received settings: ' + JSON.stringify(settings).substring(0, 100) + '...');
      
      gpsInterval = parseInt(settings.gpsInterval, 10) || 5;
      localStorage.setItem('gpsInterval', gpsInterval);
      
      var lang = settings.language || 'en';
      localStorage.setItem('language', lang);
      
      var mapSource = settings.mapSource || 'opentopomap';
      var oldMapSource = localStorage.getItem('mapSource') || 'opentopomap';
      localStorage.setItem('mapSource', mapSource);

      var oldCustomTileUrl = localStorage.getItem('customTileUrl') || '';
      var customTileUrl = settings.customTileUrl !== undefined ? settings.customTileUrl : oldCustomTileUrl;
      localStorage.setItem('customTileUrl', customTileUrl);
      if (mapSource === 'custom' && customTileUrl !== oldCustomTileUrl) {
        oldMapSource = '(custom url changed)'; // force the reload path below
      }

      var fullscreen = settings.fullscreen || false;
      var oldFullscreen = localStorage.getItem('fullscreen') === 'true';
      localStorage.setItem('fullscreen', fullscreen ? 'true' : 'false');
      
      if (fullscreen !== oldFullscreen) {
        console.log('Fullscreen setting changed from ' + oldFullscreen + ' to ' + fullscreen);
        updateMapDimensions();
      }

      var showBreadcrumbs = settings.showBreadcrumbs !== undefined ? settings.showBreadcrumbs : true;
      var oldShowBreadcrumbs = localStorage.getItem('showBreadcrumbs') !== 'false';
      localStorage.setItem('showBreadcrumbs', showBreadcrumbs ? 'true' : 'false');
      
      var dashboardFields = settings.dashboardFields !== undefined ? settings.dashboardFields : 31;
      localStorage.setItem('dashboardFields', dashboardFields.toString());

      var navViewMode = settings.navViewMode !== undefined ? settings.navViewMode : 0;
      localStorage.setItem('navViewMode', navViewMode.toString());

      if (showBreadcrumbs !== oldShowBreadcrumbs) {
        console.log('Show breadcrumbs setting changed from ' + oldShowBreadcrumbs + ' to ' + showBreadcrumbs);
        isSendingMap = false;
      }
      
      if (mapSource !== oldMapSource) {
        console.log('Map source changed from ' + oldMapSource + ' to ' + mapSource + '. Triggering map reload.');
        // Decoded tiles of the old style are now dead weight; drop them so the
        // new style does not have to wait for them to age out of the cache.
        clearDecodedTiles();
        isSendingMap = false; // Reset map sending locks if any
        // We will call updateWatchNavigationAndMap() later in the handler, but doing it here guarantees immediate response.
      }
      
      if (settings.newRoute) {
        var savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
        var newR = {
          // Route ids travel over AppMessage as int32; raw Date.now() overflows
          id: Date.now() & 0x7FFFFFFF,
          name: settings.newRoute.name || ('Route ' + (savedRoutes.length + 1)),
          points: settings.newRoute.points
        };
        savedRoutes.push(newR);
        localStorage.setItem('savedRoutes', JSON.stringify(savedRoutes));
        console.log('Added new route: ' + newR.name);
        
        // Auto-activate the newly added route
        activateSavedRoute(newR.id);
      } else {
        // Just sync routes to verify in case config changed
        syncRoutesToWatch();
      }
      
      if (settings.gpxTrack !== undefined) {
        // Legacy upload compatibility (clean up when done)
        gpxTrack = settings.gpxTrack;
        buildTrackIndex(gpxTrack);
        localStorage.setItem('gpxTrack', JSON.stringify(gpxTrack));
        if (gpxTrack.length > 0) {
          var savedRoutes = JSON.parse(localStorage.getItem('savedRoutes') || '[]');
          var autoId = Date.now() & 0x7FFFFFFF;
          var newR = {
            id: autoId,
            name: 'Import ' + new Date().toLocaleDateString(),
            points: gpxTrack
          };
          savedRoutes.push(newR);
          localStorage.setItem('savedRoutes', JSON.stringify(savedRoutes));
          localStorage.setItem('activeRouteId', autoId.toString());
          syncRoutesToWatch();
          cacheTrackTiles(gpxTrack);
        } else {
          activateSavedRoute(0);
        }
      }
      
      // Restart GPS tracking with new interval
      restartGPSTracking();
      
      // Force immediate watch update
      updateWatchNavigationAndMap();
    } catch (err) {
      console.log('Error parsing configuration response: ' + err);
    }
  }
});

// Watch messages listener (Up/Down Zoom, Map requests, Recording control)
Pebble.addEventListener('appmessage', function(e) {
  var dict = e.payload;
  console.log('Received AppMessage from watch: ' + JSON.stringify(dict));
  
  if (dict.ZOOM_LEVEL !== undefined) {
    if (dict.ZOOM_LEVEL !== currentZoom) {
      currentZoom = dict.ZOOM_LEVEL;
      schedulePrefetchAtCurrentZoom();
    }
  }
  
  if (dict.MAP_VISIBLE !== undefined) {
    var nowVisible = dict.MAP_VISIBLE === 1;
    if (nowVisible && !mapVisibleOnWatch) {
      mapVisibleOnWatch = true;
      updateWatchNavigationAndMap(); // catch up on whatever moved while hidden
    } else {
      mapVisibleOnWatch = nowVisible;
    }
  }

  if (dict.REQUEST_MAP_UPDATE !== undefined) {
    // The watch sends this alongside zoom changes: the frame it shows is
    // stale, so redraw even if the viewport looks unchanged, and assume
    // nothing about what status values it still holds.
    mapVisibleOnWatch = true; // a map request implies the map is showing
    invalidateLastRender();
    resetStatusCache();
    updateWatchNavigationAndMap();
  }
  
  if (dict.RECORDING_STATE !== undefined) {
    toggleRecordingState();
  }
  
  if (dict.ROUTE_ID !== undefined) {
    activateSavedRoute(dict.ROUTE_ID);
  }
});

function stopGPSTracking() {
  if (gpsWatchId !== null) {
    try {
      navigator.geolocation.clearWatch(gpsWatchId);
    } catch (e) {
      console.warn('Error clearing watch: ' + e);
    }
    gpsWatchId = null;
  }
  if (gpsPollTimer !== null) {
    clearInterval(gpsPollTimer);
    gpsPollTimer = null;
  }
}

function requestIdleFix() {
  try {
    navigator.geolocation.getCurrentPosition(onGPSSuccess, onGPSError, {
      enableHighAccuracy: true,
      // A fix almost as old as the poll period is still current enough for
      // the idle map/dashboard, and lets the OS answer from cache for free.
      maximumAge: IDLE_GPS_POLL_MS - 5000,
      timeout: 20000
    });
  } catch (err) {
    console.error('Error requesting position: ' + err);
    onGPSError({ message: err.message || 'Permission/Initialization error' });
  }
}

// While navigating, a continuous watch keeps the receiver locked so fixes
// arrive fresh and evenly spaced -- turn alerts and off-route detection
// depend on that. When idle there is nothing time-critical to feed, so the
// watch is dropped entirely and a periodic one-shot request lets the phone
// power the GPS receiver down between fixes.
function restartGPSTracking() {
  if (typeof navigator === 'undefined' || !navigator.geolocation) {
    console.error('Navigator or Geolocation is not available.');
    onGPSError({ message: 'Geolocation not supported' });
    return;
  }

  stopGPSTracking();

  if (isNavigating) {
    var options = {
      enableHighAccuracy: true,
      maximumAge: 10000, // allow cached location up to 10s old
      timeout: 10000     // larger timeout to avoid immediate cold start failures
    };

    try {
      gpsWatchId = navigator.geolocation.watchPosition(
        onGPSSuccess,
        onGPSError,
        options
      );
      console.log('Continuous GPS tracking started with interval: ' + gpsInterval + 's');
    } catch (err) {
      console.error('Error starting watchPosition: ' + err);
      onGPSError({ message: err.message || 'Permission/Initialization error' });
    }
  } else {
    requestIdleFix(); // immediate fix so the app is not blank until the first poll
    gpsPollTimer = setInterval(requestIdleFix, IDLE_GPS_POLL_MS);
    console.log('Idle GPS polling started, every ' + (IDLE_GPS_POLL_MS / 1000) + 's');
  }
}

function onGPSSuccess(position) {
  gpsErrorActive = false;
  var now = Date.now();
  var timediff = 0.0;
  if ( lastPositionTime ) {
    timediff = (now - lastPositionTime) / 1000;
    if ( timediff < gpsInterval ) {
      return;
    }
  }
  lastPositionTime = now;

  var lat = position.coords.latitude;
  var lon = position.coords.longitude;
  
  currentSpeed = position.coords.speed !== null && position.coords.speed !== undefined ? position.coords.speed : 0;
  currentHeading = position.coords.heading !== null && position.coords.heading !== undefined ? position.coords.heading : -1;
  
  if ( timediff > 0 && lastPositionCoords ) {
    var ds = haversineDistance(
      lastPositionCoords.latitude,
      lastPositionCoords.longitude,
      lat,
      lon
    );
    
    var calculatedSpeed = ds / timediff;
    if (position.coords.speed === null || position.coords.speed === undefined) {
      currentSpeed = calculatedSpeed;
    }
    
    if (currentHeading === -1 && calculatedSpeed > 0.8 && ds > 0.8) {
      currentHeading = getBearing(lastPositionCoords.latitude, lastPositionCoords.longitude, lat, lon);
    }
    
    if (currentSpeed > 0.5 && ds > 0.5) {
      if (isNavigating) {
        totalMovingDistance += ds;
        totalMovingTimeSec += timediff;
        // Persisted on the 10m breadcrumb cadence below
      }
    }
  }
  
  lastPositionCoords = { latitude: lat, longitude: lon };

  currentLocation = {
    lat: lat,
    lon: lon,
    speed: currentSpeed,
    altitude: position.coords.altitude || 0
  };
  currentLL = new LatLon(lat, lon);
  
  // Record coordinates walked during navigation/tracking (10m threshold)
  if (isNavigating) {
    var lastPt = recordedTrack[recordedTrack.length - 1];
    var shouldAdd = false;
    if (!lastPt) {
      shouldAdd = true;
    } else {
      var d = haversineDistance(lastPt.lat, lastPt.lon, lat, lon);
      if (d >= 10) {
        shouldAdd = true;
      }
    }
    if (shouldAdd) {
      recordedTrack.push({
        lat: lat,
        lon: lon,
        ele: position.coords.altitude || 0,
        time: now
      });
      recordedTrackTailCount++;
      if (recordedTrackTailCount >= RECORDED_TAIL_LIMIT) {
        // Fold the tail into the base: the one write whose cost grows with
        // trip length, paid once per RECORDED_TAIL_LIMIT points.
        localStorage.setItem('recordedTrack', JSON.stringify(recordedTrack));
        localStorage.setItem('recordedTrackTail', '[]');
        recordedTrackTailCount = 0;
      } else {
        localStorage.setItem('recordedTrackTail',
          JSON.stringify(recordedTrack.slice(recordedTrack.length - recordedTrackTailCount)));
      }
      // Piggyback the moving stats on the same cadence; a crash loses at
      // most the last ~10m of statistics.
      localStorage.setItem('totalMovingDistance', totalMovingDistance);
      localStorage.setItem('totalMovingTimeSec', totalMovingTimeSec);
    }
  }
  
  updateWatchNavigationAndMap();
}

function getHeadingString(heading, isEnglish) {
  if (heading < 0 || heading === null || heading === undefined) return "---";
  var val = Math.floor((heading / 22.5) + 0.5);
  var arrEn = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
  var arrDe = ["N", "NNO", "NO", "ONO", "O", "OSO", "SO", "SSO", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"];
  return isEnglish ? arrEn[(val % 16)] : arrDe[(val % 16)];
}

function onGPSError(err) {
  // pypkjs (emulator) invokes the failure callback with no argument; an
  // unguarded property access here would kill the whole JS runtime.
  console.log('GPS Error: ' + (err && err.message ? err.message : 'unknown'));

  // Error state is persistent on the watch until a successful fix clears
  // it; repeated errors (a 10s timeout loop in bad signal) carry no new
  // information and would only wake the radio.
  if (gpsErrorActive) {
    return;
  }
  gpsErrorActive = true;

  var isEnglish = localStorage.getItem('language') !== 'de';
  var fullscreenMode = localStorage.getItem('fullscreen') === 'true' ? 1 : 0;
  // Notify watch of lost connection
  sendStatusMessage({
    GPS_CONNECTED: 0,
    NAV_INSTRUCTION: isEnglish ? 'No GPS Signal' : 'Kein GPS-Signal',
    NAV_DISTANCE: '---',
    LANGUAGE: isEnglish ? 1 : 0,
    FULLSCREEN_MODE: fullscreenMode,
    DASHBOARD_FIELDS: parseInt(localStorage.getItem('dashboardFields') || '31', 10),
    NAV_VIEW_MODE: parseInt(localStorage.getItem('navViewMode') || '0', 10),
    GPS_ALT_STR: "---",
    HEADING_STR: "---"
  });
}

// Perform calculations and send updates to watch
function updateWatchNavigationAndMap() {
  var isEnglish = localStorage.getItem('language') !== 'de';
  var activeRouteId = parseInt(localStorage.getItem('activeRouteId') || '0', 10);
  var fullscreenMode = localStorage.getItem('fullscreen') === 'true' ? 1 : 0;
  
  if (!currentLocation) {
    sendStatusMessage({
      GPS_CONNECTED: 0,
      LANGUAGE: isEnglish ? 1 : 0,
      RECORDING_STATE: isNavigating ? 1 : 0,
      ACTIVE_ROUTE_ID: activeRouteId,
      FULLSCREEN_MODE: fullscreenMode,
      DASHBOARD_FIELDS: parseInt(localStorage.getItem('dashboardFields') || '31', 10),
      NAV_VIEW_MODE: parseInt(localStorage.getItem('navViewMode') || '0', 10),
      GPS_ALT_STR: "---",
      HEADING_STR: "---"
    });
    return;
  }
  
  var avgSpeedKmh = totalMovingTimeSec > 0 ? (totalMovingDistance / totalMovingTimeSec) * 3.6 : 0;
  var payload = {
    GPS_CONNECTED: 1,
    AVG_SPEED: avgSpeedKmh.toFixed(1),
    GPS_COORDS: currentLocation.lat.toFixed(5) + ', ' + currentLocation.lon.toFixed(5),
    LANGUAGE: isEnglish ? 1 : 0,
    RECORDING_STATE: isNavigating ? 1 : 0,
    GPS_SPEED: Math.round(currentSpeed * 100),
    GPS_HEADING: Math.round(currentHeading),
    ACTIVE_ROUTE_ID: activeRouteId,
    FULLSCREEN_MODE: fullscreenMode,
    DASHBOARD_FIELDS: parseInt(localStorage.getItem('dashboardFields') || '31', 10),
    NAV_VIEW_MODE: parseInt(localStorage.getItem('navViewMode') || '0', 10),
    GPS_ALT_STR: Math.round(currentLocation.altitude) + 'm',
    HEADING_STR: getHeadingString(currentHeading, isEnglish)
  };

  var offRoute = false;
  var vibrateAlert = 0;

  if (gpxTrack.length > 0) {
    var trackLengthMinusOne = gpxTrack.length - 1;
    if (!trackIndex || trackIndex.ll.length !== gpxTrack.length) {
      buildTrackIndex(gpxTrack); // safety net; normally built on track change
    }

    // 1. Find the closest point on the track.
    // Get the section we're on. closestIdx is the start of that section
    // (which we already passed). Position changes little between fixes, so
    // search a window around the previous match first and fall back to the
    // full track only when the window result is implausibly far (GPS jump,
    // stale index from a previous session).
    var SEARCH_WINDOW = 40; // points each way
    var FULL_RESCAN_DIST = 75; // m; comfortably above the 50m off-route line
    var lastIdx = closestTrackPointIdx;
    var found = null;
    if (lastIdx >= 0 && lastIdx <= trackLengthMinusOne) {
      found = findClosestOnTrack(
        Math.max(0, lastIdx - SEARCH_WINDOW),
        Math.min(trackLengthMinusOne, lastIdx + SEARCH_WINDOW)
      );
      if (found.minDist > FULL_RESCAN_DIST) {
        found = null;
      }
    }
    if (!found) {
      found = findClosestOnTrack(0, trackLengthMinusOne);
    }
    var minDist = found.minDist;
    var closestIdx = found.closestIdx;
    // The closest match can be the final track point, where "the point
    // after it" does not exist; all lookahead math targets nextIdx instead
    // of closestIdx + 1 so reaching the destination cannot read past the
    // track (remaining distances degrade to the distance to the last point).
    var nextIdx = Math.min(closestIdx + 1, trackLengthMinusOne);

    // Save closest index for map rendering (gray out walked part)
    if (closestIdx !== closestTrackPointIdx) {
      closestTrackPointIdx = closestIdx;
      localStorage.setItem('closestTrackPointIdx', closestTrackPointIdx);
    }

    // Distance traveled and remaining, from the prefix sums
    var cumDist = trackIndex.cumDist;
    var walkedDist = closestIdx >= 1 ? cumDist[closestIdx - 1] : 0;
    walkedDist += haversineDistance(gpxTrack[closestIdx].lat, gpxTrack[closestIdx].lon, currentLocation.lat, currentLocation.lon);
    var remDist = haversineDistance(currentLocation.lat, currentLocation.lon, gpxTrack[nextIdx].lat, gpxTrack[nextIdx].lon);
    remDist += cumDist[trackLengthMinusOne] - cumDist[nextIdx];
    payload.TRIP_DISTANCE = (walkedDist / 1000).toFixed(1) + ' ' + (remDist / 1000).toFixed(1);

    // Elevation stats from the prefix sums
    var gainMade = trackIndex.cumGain[closestIdx];
    var lossMade = trackIndex.cumLoss[closestIdx];
    var gainRemaining = trackIndex.cumGain[trackLengthMinusOne] - gainMade;
    var lossRemaining = trackIndex.cumLoss[trackLengthMinusOne] - lossMade;

    payload.ELEVATION_GAIN = Math.round(gainMade) + ' ' + Math.round(gainRemaining);
    payload.ELEVATION_LOSS = Math.round(lossMade) + ' ' + Math.round(lossRemaining);
    
    // Check if user is Off-Route (> 50 meters)
    if (minDist > 50) {
      offRoute = true;
      payload.OFF_ROUTE = 1;
      payload.NAV_INSTRUCTION = isEnglish ? 'OFF ROUTE!' : 'ABSEITS DER ROUTE!';
      payload.NAV_DISTANCE = Math.round(minDist) + 'm';
      payload.NAV_BEARING = -1;
      
      // Trigger off-route vibration alert once
      if (!hasVibratedOffRoute) {
        vibrateAlert = 2; // Off-Route alert
        hasVibratedOffRoute = true;
      }
    } else {
      payload.OFF_ROUTE = 0;
      hasVibratedOffRoute = false; // Reset off-route vibration state once back on route
      
      // 2. Look ahead for significant turns
      var turnIdx = -1;
      var distToTurn = haversineDistance(currentLocation.lat, currentLocation.lon, gpxTrack[nextIdx].lat, gpxTrack[nextIdx].lon);
      var turnBearingDiff = 0;

      // Check all remaining trackpoints for bearing changes and measure the
      // distance to the first significant change (precomputed bearings).
      var previousBearing = trackIndex.bearings[closestIdx];
      for (var idx = closestIdx + 1; idx < trackLengthMinusOne; idx++) {
        var nextBearing = trackIndex.bearings[idx];
        // +540 keeps the dividend positive: JS % keeps the sign of the
        // dividend, so +180 alone would map raw diffs below -180 outside
        // the target range and flip the turn direction.
        var diff = ((nextBearing - previousBearing + 540) % 360) - 180; // diff in [-180, 180)
        if (Math.abs(diff) > 30) {
          turnIdx = idx;
          turnBearingDiff = diff;
          break;
        }
        previousBearing = nextBearing;
      }
      // Add the distance from the next track point to the turn (or track
      // end), from the prefix sums.
      distToTurn += cumDist[turnIdx !== -1 ? turnIdx : trackLengthMinusOne] - cumDist[nextIdx];

      if (distToTurn > 1000) {
         payload.NAV_DISTANCE = (distToTurn / 1000).toFixed(1) + 'km';
      } else {
         payload.NAV_DISTANCE = Math.round(distToTurn) + 'm';
      }

      if (turnIdx !== -1) {
        
        // Formulate instruction text
        var dirText = '';
        if (isEnglish) {
          dirText = turnBearingDiff > 0 ? 'Right' : 'Left';
        } else {
          dirText = turnBearingDiff > 0 ? 'Rechts' : 'Links';
        }
        payload.NAV_INSTRUCTION = dirText + ' in ' + payload.NAV_DISTANCE;
        
        // Map bearing to 0=straight, 90=right, 180=uturn, 270=left
        payload.NAV_BEARING = turnBearingDiff > 0 ? 90 : 270;
        
        // Trigger turn haptic vibration and popup at ~50 meters (only once per turn)
        if (distToTurn <= 50) {
          if (lastVibratedTurnIdx !== turnIdx) {
            vibrateAlert = turnBearingDiff > 0 ? 3 : 1; // 3 = Right, 1 = Left
            lastVibratedTurnIdx = turnIdx;
            if (localStorage.getItem('navViewMode') !== '1') { // 1 = Map Only, so 0 and 2 will show popup
              payload.NAV_POPUP_STATE = 1;
            } else {
              payload.NAV_POPUP_STATE = 0;
            }
          }
        } else {
          payload.NAV_POPUP_STATE = 0;
        }
      } else {
        // No more sharp turns.
        payload.NAV_INSTRUCTION = (isEnglish ? 'Straight for ' : 'Gerade aus ') + payload.NAV_DISTANCE;
        payload.NAV_BEARING = 0; // straight
        payload.NAV_POPUP_STATE = 0;
      }
    }
  } else {
    payload.NAV_INSTRUCTION = isEnglish ? 'No route' : 'Keine Route';
    payload.NAV_DISTANCE = '---';
    payload.TRIP_DISTANCE = '--- ---';
    payload.ELEVATION_GAIN = '--- ---';
    payload.ELEVATION_LOSS = '--- ---';
    payload.NAV_POPUP_STATE = 0;
    closestTrackPointIdx = -1;
  }
  
  if (vibrateAlert !== 0) {
    payload.VIBRATE_ALERT = vibrateAlert;
  }
  
  // Send status/nav values first (only keys that changed go over the air)
  sendStatusMessage(payload, function() {
    // Render and send the map image afterward
    renderAndSendMap();
  }, function(e) {
    console.log('AppMessage send failed: ' + JSON.stringify(e));
    // Still try to send the map
    renderAndSendMap();
  });
}

// Decoded tiles, keyed by their localStorage key. Without this every render
// re-runs base64 decoding and png.decodePNG over the whole viewport, which is
// the bulk of the phone-side work for a map that has barely moved. A decoded
// tile is 256*256*4 bytes of RGBA, so only a few are held: the viewport spans
// at most four, and the spare slots give panning some hysteresis.
var DECODED_TILE_LIMIT = 6;
var decodedTiles = {};
var decodedTileOrder = []; // same keys, least recently used first

// Tiles whose download recently failed (offline, 404, server error). The
// negative cache keeps a permanently unavailable tile from being re-requested
// on every render.
var TILE_FAIL_RETRY_MS = 60 * 1000;
var failedTiles = {};

function tileRecentlyFailed(storeKey) {
  var failedAt = failedTiles[storeKey];
  return failedAt !== undefined && (Date.now() - failedAt) < TILE_FAIL_RETRY_MS;
}

// --- Persistent tile cache accounting (LRU under a discovered cap) ---
// localStorage is a shared pool (also holding routes and trips) whose real
// quota varies wildly between phone apps and there is no API to query it.
// Rather than assuming a size, tiles are stored freely until a write throws
// QuotaExceededError; that failure point IS the capacity probe. 90% of it
// is persisted as the cap (headroom for routes/trips growing later), and
// each session start raises the cap by 10% so capacity freed since (deleted
// trips, larger quota) gets re-discovered instead of staying locked out.
// Tiles are tracked in an index (storeKey -> last-use time and size); the
// least recently used ones are evicted to keep the total under the cap.
var TILE_INDEX_KEY = 'tileCacheIndex';
var TILE_CACHE_CAP_KEY = 'tileCacheCapBytes';
var TILE_CACHE_MIN_CAP = 512 * 1024; // even a tiny quota keeps a few tiles
var tileCacheCapBytes = null; // null: no quota error seen yet, store freely
var tileIndex = {};
var tileCacheBytes = 0;
var tileIndexFlushTimer = null;

function tileCacheDebugString() {
  var count = 0;
  for (var k in tileIndex) {
    if (tileIndex.hasOwnProperty(k)) count++;
  }
  var capStr = tileCacheCapBytes === null ? 'no cap discovered' :
               'cap ' + (tileCacheCapBytes / (1024 * 1024)).toFixed(2) + ' MB';
  return count + ' tiles, ' + (tileCacheBytes / (1024 * 1024)).toFixed(2) +
         ' MB (' + capStr + ')';
}

// Called when localStorage.setItem threw: the current fill level is the
// most accurate capacity measurement available.
function discoverTileCacheCap() {
  tileCacheCapBytes = Math.max(TILE_CACHE_MIN_CAP, Math.floor(tileCacheBytes * 0.9));
  try {
    localStorage.setItem(TILE_CACHE_CAP_KEY, String(tileCacheCapBytes));
  } catch (e) {}
  console.log('Tile cache: quota hit, cap discovered at ' + tileCacheDebugString());
}

// The index itself is persisted lazily -- recency bookkeeping is not worth
// a localStorage write per touched tile per render.
function flushTileIndexSoon() {
  if (tileIndexFlushTimer) return;
  tileIndexFlushTimer = setTimeout(function() {
    tileIndexFlushTimer = null;
    try {
      localStorage.setItem(TILE_INDEX_KEY, JSON.stringify(tileIndex));
    } catch (e) {
      console.warn('Could not persist tile index: ' + e);
    }
  }, 5000);
}

// Tiles stored by older app versions predate the index; adopt them with a
// last-use of 0 so they are first in line for eviction. Key enumeration may
// be unsupported in some PKJS runtimes -- skip silently then.
function adoptUntrackedTiles() {
  try {
    var adopted = 0;
    for (var i = 0; i < localStorage.length; i++) {
      var key = localStorage.key(i);
      if (key && key.indexOf('tile_') === 0 && !tileIndex[key]) {
        var value = localStorage.getItem(key);
        if (value) {
          tileIndex[key] = { t: 0, s: value.length };
          tileCacheBytes += value.length;
          adopted++;
        }
      }
    }
    if (adopted) {
      console.log('Tile cache: adopted ' + adopted + ' untracked legacy tiles');
      flushTileIndexSoon();
    }
  } catch (e) {
    // Enumeration unsupported; legacy tiles get adopted on first use instead
  }
}

function loadTileIndex() {
  try {
    tileIndex = JSON.parse(localStorage.getItem(TILE_INDEX_KEY) || '{}');
  } catch (e) {
    tileIndex = {};
  }
  tileCacheBytes = 0;
  for (var k in tileIndex) {
    if (tileIndex.hasOwnProperty(k)) tileCacheBytes += tileIndex[k].s;
  }
  var storedCap = parseInt(localStorage.getItem(TILE_CACHE_CAP_KEY) || '', 10);
  if (storedCap > 0) {
    // The 10% raise is in-memory only; it persists on the next quota error
    tileCacheCapBytes = Math.floor(storedCap * 1.1);
  }
  adoptUntrackedTiles();
}

// Refresh recency on a cache hit (adopting legacy entries the enumeration
// sweep could not see).
function touchTile(storeKey, size) {
  var entry = tileIndex[storeKey];
  if (entry) {
    entry.t = Date.now();
  } else {
    tileIndex[storeKey] = { t: Date.now(), s: size };
    tileCacheBytes += size;
  }
  flushTileIndexSoon();
}

function evictLRUTiles(bytesToFree) {
  var freed = 0;
  var evicted = 0;
  while (freed < bytesToFree) {
    var oldestKey = null;
    var oldestT = Infinity;
    for (var k in tileIndex) {
      if (tileIndex.hasOwnProperty(k) && tileIndex[k].t < oldestT) {
        oldestT = tileIndex[k].t;
        oldestKey = k;
      }
    }
    if (!oldestKey) break;
    freed += tileIndex[oldestKey].s;
    tileCacheBytes -= tileIndex[oldestKey].s;
    delete tileIndex[oldestKey];
    try {
      localStorage.removeItem(oldestKey);
    } catch (e) {}
    evicted++;
  }
  if (evicted) {
    console.log('Tile cache: evicted ' + evicted + ' LRU tiles (' +
                Math.round(freed / 1024) + ' KB); now ' + tileCacheDebugString());
    flushTileIndexSoon();
  }
}

// Store a tile under the discovered cap. allowEvict distinguishes the two
// callers: the render path may push out older tiles (the user is looking at
// this one right now), while prefetch must stop at the cap instead --
// evicting prefetched tiles to store more prefetch just burns downloads.
// Returns false when the tile was not persisted.
function storeTile(storeKey, base64, allowEvict) {
  var size = base64.length;
  var prevSize = tileIndex[storeKey] ? tileIndex[storeKey].s : 0;
  var projected = tileCacheBytes - prevSize + size;
  if (tileCacheCapBytes !== null && projected > tileCacheCapBytes) {
    if (!allowEvict) return false;
    evictLRUTiles(projected - tileCacheCapBytes);
  }
  try {
    localStorage.setItem(storeKey, base64);
  } catch (e) {
    // The write itself is the capacity probe: adopt the failure point as
    // the cap (also clamps a stale cap down when routes/trips have grown),
    // then evict and retry once for the render path.
    discoverTileCacheCap();
    if (!allowEvict) return false;
    evictLRUTiles(Math.max(size * 4, 256 * 1024));
    try {
      localStorage.setItem(storeKey, base64);
    } catch (e2) {
      console.warn('Tile store failed even after eviction: ' + e2);
      return false;
    }
  }
  // Eviction above may have removed this very key; re-read its indexed size
  // so the byte total stays consistent with the index.
  prevSize = tileIndex[storeKey] ? tileIndex[storeKey].s : 0;
  tileCacheBytes += size - prevSize;
  tileIndex[storeKey] = { t: Date.now(), s: size };
  flushTileIndexSoon();
  return true;
}

function getDecodedTile(storeKey) {
  var tile = decodedTiles[storeKey];
  if (!tile) return null;
  putDecodedTile(storeKey, tile); // refresh recency
  return tile;
}

function putDecodedTile(storeKey, tile) {
  var idx = decodedTileOrder.indexOf(storeKey);
  if (idx !== -1) {
    decodedTileOrder.splice(idx, 1);
  }
  decodedTiles[storeKey] = tile;
  decodedTileOrder.push(storeKey);

  while (decodedTileOrder.length > DECODED_TILE_LIMIT) {
    delete decodedTiles[decodedTileOrder.shift()];
  }
}

function clearDecodedTiles() {
  decodedTiles = {};
  decodedTileOrder = [];
}

// Everything renderViewport() draws that is not the map centre. Any change
// here means the image differs even if the watch has not moved.
function getRenderSignature() {
  return [
    currentZoom,
    MAP_WIDTH,
    MAP_HEIGHT,
    localStorage.getItem('mapSource') || 'opentopomap',
    localStorage.getItem('showBreadcrumbs') !== 'false',
    localStorage.getItem('activeRouteId') || '0',
    closestTrackPointIdx,
    gpxTrack.length,
    recordedTrack.length
  ].join('|');
}

// Drop the cached render so the next update redraws unconditionally. Needed
// whenever the watch may have lost the image we think it is showing.
function invalidateLastRender() {
  lastRender = null;
  lastDeliveredFrameHash = null;
}

// FNV-1a over the raw frame. Two renders with equal hashes are treated as
// the same image, so a frame identical to what the watch already shows is
// never re-sent.
function hashFrame(bytes) {
  var h = 0x811c9dc5;
  for (var i = 0; i < bytes.length; i++) {
    h ^= bytes[i];
    // h *= 16777619 (mod 2^32), written with shifts to stay in int32 ops
    h = (h + (h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24)) >>> 0;
  }
  return h;
}

// PackBits-style RLE. Control byte c: c < 128 means c+1 literal bytes
// follow; c > 128 means the next byte repeats 257-c times; 128 is unused.
// Quantized 64-color map imagery is dominated by flat runs, so this
// typically shrinks a frame several-fold at negligible cost on both ends.
function packBitsEncode(bytes) {
  var out = [];
  var len = bytes.length;
  var i = 0;

  while (i < len) {
    var b = bytes[i];
    var run = 1;
    while (run < 128 && i + run < len && bytes[i + run] === b) {
      run++;
    }

    if (run >= 2) {
      out.push(257 - run, b);
      i += run;
      continue;
    }

    // Literal stretch: extend until the next run of 3+ starts (a 2-run is
    // no cheaper as a repeat than as two literals) or the 128 cap.
    var start = i;
    i++;
    while (i < len && i - start < 128) {
      if (i + 2 < len && bytes[i] === bytes[i + 1] && bytes[i] === bytes[i + 2]) {
        break;
      }
      i++;
    }
    out.push(i - start - 1);
    for (var j = start; j < i; j++) {
      out.push(bytes[j]);
    }
  }

  return new Uint8Array(out);
}

// Render viewport tiles and send map image in chunks
function renderAndSendMap() {
  if (isSendingMap || !currentLocation) return;

  // No map pixels are visible on the watch right now: hidden by the
  // dashboard/menu/popup (reported by the watch) or the user runs in Arrow
  // Only mode, where the watch never draws the map at all.
  if (!mapVisibleOnWatch) return;
  if (parseInt(localStorage.getItem('navViewMode') || '0', 10) === 2) return;

  // 1. Identify which tiles are needed for the current viewport
  var centerPix = graphics.latLonToPixels(currentLocation.lat, currentLocation.lon, currentZoom);
  var signature = getRenderSignature();

  // Nothing the render depends on has changed: the watch is already showing
  // this exact image, so skip the decode, rasterize and transfer entirely.
  if (lastRender &&
      lastRender.signature === signature &&
      Math.abs(centerPix.x - lastRender.x) < RENDER_PIXEL_THRESHOLD &&
      Math.abs(centerPix.y - lastRender.y) < RENDER_PIXEL_THRESHOLD) {
    return;
  }

  isSendingMap = true;
  pendingRender = { x: centerPix.x, y: centerPix.y, signature: signature };

  var tlX = centerPix.x - MAP_WIDTH / 2;
  var tlY = centerPix.y - MAP_HEIGHT / 2;
  var tileXMin = Math.floor(tlX / 256);
  var tileXMax = Math.floor((tlX + MAP_WIDTH) / 256);
  var tileYMin = Math.floor(tlY / 256);
  var tileYMax = Math.floor((tlY + MAP_HEIGHT) / 256);
  
  var tileCache = {};
  var tilesToFetch = [];
  var requiredKeys = [];
  var mapSource = localStorage.getItem('mapSource') || 'opentopomap';

  for (var tx = tileXMin; tx <= tileXMax; tx++) {
    for (var ty = tileYMin; ty <= tileYMax; ty++) {
      var key = currentZoom + '/' + tx + '/' + ty;
      var storeKey = 'tile_' + mapSource + '_' + key;
      requiredKeys.push(key);

      var memoryTile = getDecodedTile(storeKey);
      if (memoryTile) {
        tileCache[key] = memoryTile;
        continue;
      }

      var cachedBase64 = localStorage.getItem(storeKey);

      if (cachedBase64) {
        touchTile(storeKey, cachedBase64.length);
        try {
          var bytes = base64ToUint8Array(cachedBase64);
          var decoded = png.decodePNG(bytes);
          tileCache[key] = decoded;
          putDecodedTile(storeKey, decoded);
        } catch (err) {
          console.log('Cached tile decode error (' + key + '): ' + err);
          if (!tileRecentlyFailed(storeKey)) {
            tilesToFetch.push({ key: key, z: currentZoom, x: tx, y: ty });
          }
        }
      } else if (!tileRecentlyFailed(storeKey)) {
        // Tile not cached, fetch online
        tilesToFetch.push({ key: key, z: currentZoom, x: tx, y: ty });
      }
    }
  }
  
  // 2. Fetch missing tiles if online
  if (tilesToFetch.length > 0) {
    var fetchedCount = 0;
    
    function checkCompleted() {
      fetchedCount++;
      if (fetchedCount === tilesToFetch.length) {
        doRenderAndChunkSend(tileCache, requiredKeys);
      }
    }
    
    tilesToFetch.forEach(function(item) {
      var url = getTileUrl(item.z, item.x, item.y);
      
      var xhr = new XMLHttpRequest();
      xhr.open('GET', url, true);
      xhr.responseType = 'arraybuffer';
      
      xhr.onload = function() {
        var itemStoreKey = 'tile_' + mapSource + '_' + item.key;
        if (xhr.status === 200) {
          try {
            var bytes = new Uint8Array(xhr.response);
            var decoded = png.decodePNG(bytes);
            tileCache[item.key] = decoded;
            putDecodedTile(itemStoreKey, decoded);
            delete failedTiles[itemStoreKey];

            // Cache in localStorage, evicting LRU tiles for room; a failed
            // store only costs a future re-download, the decoded tile is
            // already usable for this render.
            storeTile(itemStoreKey, arrayBufferToBase64(xhr.response), true);
          } catch (e) {
            console.log('Error decoding fetched tile ' + item.key + ': ' + e);
            failedTiles[itemStoreKey] = Date.now();
          }
        } else {
          failedTiles[itemStoreKey] = Date.now();
        }
        checkCompleted();
      };
      xhr.onerror = function() {
        console.error('Failed to fetch tile: ' + item.key);
        failedTiles['tile_' + mapSource + '_' + item.key] = Date.now();
        checkCompleted();
      };
      xhr.send();
    });
  } else {
    doRenderAndChunkSend(tileCache, requiredKeys);
  }
}

// Draw route overlays and trigger the AppMessage transmission loop
function doRenderAndChunkSend(tileCache, requiredKeys) {
  try {
    // A viewport drawn with tiles that failed to load is only provisional: it
    // must not be remembered as current, or the blank patches would stick
    // until the watch moves far enough to trigger a redraw.
    var allTilesPresent = true;
    for (var i = 0; i < requiredKeys.length; i++) {
      if (!tileCache[requiredKeys[i]]) {
        allTilesPresent = false;
        break;
      }
    }

    var showBreadcrumbs = localStorage.getItem('showBreadcrumbs') !== 'false';
    var gcolor8Map = graphics.renderViewport(
      currentLocation.lat,
      currentLocation.lon,
      currentZoom,
      gpxTrack,
      tileCache,
      closestTrackPointIdx,
      recordedTrack,
      showBreadcrumbs
    );

    // The watch already shows these exact pixels -- skip the whole transfer.
    // Catches, among others, a stationary user whose viewport has missing
    // tiles (lastRender stays unset there, so only the hash prevents an
    // endless re-send of the identical frame).
    var frameHash = hashFrame(gcolor8Map);
    if (frameHash === lastDeliveredFrameHash) {
      lastRender = allTilesPresent ? pendingRender : null;
      isSendingMap = false;
      return;
    }

    // Compress; fall back to the raw frame in the (pathological) case where
    // RLE would expand it.
    var encoded = packBitsEncode(gcolor8Map);
    var useRle = encoded.length < gcolor8Map.length;
    var sendData = useRle ? encoded : gcolor8Map;
    console.log('Map frame: ' + gcolor8Map.length + 'B raw -> ' + sendData.length +
                'B ' + (useRle ? 'rle' : 'raw'));

    // Chunked Transmission Loop
    var totalSize = sendData.length;
    var totalChunks = Math.ceil(totalSize / CHUNK_SIZE);

    function sendChunk(chunkIdx) {
      if (chunkIdx >= totalChunks) {
        console.log('Map image fully transmitted to watch!');
        lastDeliveredFrameHash = frameHash;
        lastRender = allTilesPresent ? pendingRender : null;
        isSendingMap = false;
        return;
      }

      var start = chunkIdx * CHUNK_SIZE;
      var end = Math.min(start + CHUNK_SIZE, totalSize);
      var chunkData = Array.prototype.slice.call(sendData.subarray(start, end));

      var payload = {
        MAP_DATA_CHUNK: chunkData,
        CHUNK_INDEX: chunkIdx,
        TOTAL_CHUNKS: totalChunks,
        MAP_ENCODING: useRle ? 1 : 0,
        MAP_TOTAL_BYTES: totalSize
      };
      
      var retries = 0;
      function transmit() {
        Pebble.sendAppMessage(payload, function() {
          // Success, send next chunk
          sendChunk(chunkIdx + 1);
        }, function(err) {
          console.warn('Chunk ' + chunkIdx + ' failed sending. Retrying...');
          retries++;
          if (retries < 3) {
            setTimeout(transmit, 150);
          } else {
            console.error('Failed transmitting map chunk ' + chunkIdx + ' after 3 retries.');
            invalidateLastRender(); // watch holds a partial image
            isSendingMap = false;
          }
        });
      }
      transmit();
    }
    
    sendChunk(0);
  } catch (err) {
    console.error('Map rendering / transmission crashed: ' + err.stack);
    invalidateLastRender();
    isSendingMap = false;
  }
}

// Background Tile Cacher along the GPX Track. Prefetches at the zoom that is
// actually being displayed -- caching a level nobody looks at means every
// tile on the trail still goes over the cellular radio at view time.
var PREFETCH_TILE_CAP = 200; // bounds per-run work; storeTile's discovered cap is the hard limit
var prefetchRunToken = 0;
var prefetchDebounceTimer = null;

function cacheTrackTiles(track) {
  var zoom = currentZoom;
  var tileKeys = [];
  var seen = {};
  var capped = false;

  for (var i = 0; i < track.length && !capped; i++) {
    var pt = track[i];
    var tile = graphics.latLonToPixels(pt.lat, pt.lon, zoom);
    var tileX = Math.floor(tile.x / 256);
    var tileY = Math.floor(tile.y / 256);

    // Cache 3x3 block around track points
    for (var dx = -1; dx <= 1 && !capped; dx++) {
      for (var dy = -1; dy <= 1; dy++) {
        var key = zoom + '/' + (tileX + dx) + '/' + (tileY + dy);
        if (!seen[key]) {
          seen[key] = true;
          tileKeys.push({ key: key, z: zoom, x: tileX + dx, y: tileY + dy });
          if (tileKeys.length >= PREFETCH_TILE_CAP) {
            capped = true;
            break;
          }
        }
      }
    }
  }

  console.log('Background Tile Cache Scheduler: ' + tileKeys.length + ' tiles at zoom ' + zoom +
              (capped ? ' (CAPPED at ' + PREFETCH_TILE_CAP + ', tail of route not prefetched)' : ''));

  // A newer run (route change, zoom change) invalidates this one
  prefetchRunToken++;
  var runToken = prefetchRunToken;

  var idx = 0;
  function downloadNext() {
    if (runToken !== prefetchRunToken) {
      return; // superseded
    }
    if (idx >= tileKeys.length) {
      console.log('Offline tile caching fully completed! (' + tileCacheDebugString() + ')');
      return;
    }

    var mapSource = localStorage.getItem('mapSource') || 'opentopomap';
    var item = tileKeys[idx];
    var storeKey = 'tile_' + mapSource + '_' + item.key;

    if (localStorage.getItem(storeKey) || tileRecentlyFailed(storeKey)) {
      idx++;
      downloadNext();
      return;
    }

    var url = getTileUrl(item.z, item.x, item.y);

    var xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.responseType = 'arraybuffer';

    xhr.onload = function() {
      if (xhr.status === 200) {
        if (storeTile(storeKey, arrayBufferToBase64(xhr.response), false)) {
          delete failedTiles[storeKey];
        } else {
          console.log('Tile cache cap reached, stopping prefetch (' + tileCacheDebugString() + ')');
          return;
        }
      } else {
        failedTiles[storeKey] = Date.now();
      }
      idx++;
      setTimeout(downloadNext, 120); // rate limiting request
    };
    xhr.onerror = function() {
      failedTiles[storeKey] = Date.now();
      idx++;
      setTimeout(downloadNext, 120);
    };
    xhr.send();
  }

  downloadNext();
}

// Zoom changes arrive per button press; wait for the user to settle before
// re-running the prefetch pass at the new level.
function schedulePrefetchAtCurrentZoom() {
  if (prefetchDebounceTimer) {
    clearTimeout(prefetchDebounceTimer);
  }
  prefetchDebounceTimer = setTimeout(function() {
    prefetchDebounceTimer = null;
    if (gpxTrack.length > 0) {
      cacheTrackTiles(gpxTrack);
    }
  }, 10000);
}
